# Generated by Django 6.0 on 2026-01-14 08:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Ödül Adı')),
                ('bedel', models.IntegerField(verbose_name='Yıldız Bedeli')),
                ('resim', models.ImageField(blank=True, upload_to='oduller/', verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Ödül',
                'verbose_name_plural': 'Ödül Kataloğu',
            },
        ),
        migrations.CreateModel(
            name='AntrenorProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yas', models.IntegerField(verbose_name='Yaş')),
                ('uzmanlik_alani', models.CharField(choices=[('FITNESS', 'Fitness & Vücut Geliştirme'), ('PILATES', 'Pilates & Yoga'), ('KILO_VERME', 'Kilo Verme & Diyet'), ('KONDISYON', 'Atletik Performans & Kondisyon'), ('REHAB', 'Fizik Tedavi & Rehabilitasyon')], max_length=20, verbose_name='Uzmanlık Alanı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antrenor_profili', to=settings.AUTH_USER_MODEL, verbose_name='Antrenör')),
            ],
            options={
                'verbose_name': 'Antrenör Profili',
                'verbose_name_plural': 'Antrenör Profilleri',
            },
        ),
        migrations.CreateModel(
            name='Davet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('KABUL', 'Kabul Edildi'), ('RED', 'Reddedildi')], default='BEKLIYOR', max_length=10, verbose_name='Durum')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelen_davetler', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.antrenorprofil', verbose_name='Antrenör')),
            ],
            options={
                'verbose_name': 'Antrenör Daveti',
                'verbose_name_plural': 'Antrenör Davetleri',
            },
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=datetime.date.today, verbose_name='Tarih')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tur', models.CharField(choices=[('ANTREMAN', 'Antrenman'), ('BESLENME', 'Beslenme')], max_length=10, verbose_name='Tür')),
                ('yapildi_mi', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görev Listesi',
            },
        ),
        migrations.CreateModel(
            name='KazanilanOdul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kazanilma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kazanılma Tarihi')),
                ('teslim_edildi', models.BooleanField(default=False, verbose_name='Teslim Edildi mi?')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
                ('odul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.odul', verbose_name='Kazanılan Ödül')),
            ],
            options={
                'verbose_name': 'Kazanılan Ödül',
                'verbose_name_plural': 'Kazanılan Ödüller',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.IntegerField(help_text='Santimetre (Örn: 180)', verbose_name='Boy (cm)')),
                ('kilo', models.FloatField(help_text='Kilogram (Örn: 85.5)', verbose_name='Kilo (kg)')),
                ('yas', models.IntegerField(default=18, verbose_name='Yaş')),
                ('yildiz_bakiyesi', models.IntegerField(default=0, verbose_name='Yıldız Bakiyesi')),
                ('antrenor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogrenciler', to='core.antrenorprofil', verbose_name='Antrenörü')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Öğrenci Profili',
                'verbose_name_plural': 'Öğrenci Profilleri',
            },
        ),
    ]
