# Generated by Django 6.0 on 2025-12-07 10:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('bedel', models.IntegerField()),
                ('resim', models.ImageField(blank=True, upload_to='oduller/')),
            ],
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=datetime.date.today)),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('tur', models.CharField(choices=[('ANTREMAN', 'Antrenman'), ('BESLENME', 'Beslenme')], max_length=10)),
                ('yapildi_mi', models.BooleanField(default=False)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KazanilanOdul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kazanilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('teslim_edildi', models.BooleanField(default=False)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('odul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.odul')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.IntegerField(help_text='Santimetre cinsinden (Örn: 180)')),
                ('kilo', models.FloatField(help_text='Kilogram cinsinden (Örn: 85.5)')),
                ('yildiz_bakiyesi', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
