# Generated by Django 6.0 on 2026-01-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egzersiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=150, verbose_name='Egzersiz Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Nasıl Yapılır?')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Video Linki (Opsiyonel)')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egzersizler', to='core.antrenorprofil', verbose_name='Antrenör')),
            ],
            options={
                'verbose_name': 'Egzersiz',
                'verbose_name_plural': 'Egzersiz Kütüphanesi',
            },
        ),
    ]
