# Generated by Django 6.0 on 2026-01-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_egzersiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntrenmanHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_sayisi', models.CharField(max_length=50, verbose_name='Set')),
                ('tekrar_sayisi', models.CharField(max_length=50, verbose_name='Tekrar')),
                ('egzersiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.egzersiz')),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='core.gorev')),
            ],
        ),
    ]
