# Generated by Django 6.0 on 2026-01-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_antrenmanhareket'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrenmanhareket',
            name='yapildi_mi',
            field=models.BooleanField(default=False, verbose_name='Yapıldı'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='durum',
            field=models.CharField(choices=[('ATANDI', 'Atandı (Yapılmayı Bekliyor)'), ('ONAY_BEKLIYOR', 'Öğrenci Bitirdi (Hoca Onayı Bekliyor)'), ('TAMAMLANDI', 'Onaylandı ve Bitti')], default='ATANDI', max_length=15, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='yapildi_mi',
            field=models.BooleanField(default=False, verbose_name='Genel Tamamlanma'),
        ),
    ]
